#!/bin/bash
#8.x include 7 repos,which list in work_git
#tools,licensed,shared are not needed to be changed by me. only when need to sync to mainline, we need to update it
#these 3 repos remain at latest mainline repos.
pwd|grep c2c > /dev/null
if [ $? -eq 0 ];then
	cd ~/work/dev/c2c
	work_git="ap common opensource gateway tools licensed shared shared-old"
else
	cd ~/work/dev/mainline
	work_git="ap common opensource gateway tools licensed shared shared-old"
fi
echo -e "\033[33mwork space is `pwd`\033[0m"
for file in $work_git
do
	cd $file

	if [ $file = "shared" ] || [ $file = "shared-old" ] ; then
		echo $@ |grep c2c > /dev/null
		if [ $? -eq 0 ];then
			MYGIT="git ${@/c2c/mainline}" 
		fi
	else
		MYGIT="git $@"
	fi
	echo -e "\033[32m$MYGIT for $file\033[0m"
	$MYGIT

	cd ..
done
